server:
  port: 8089
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/favResturantdb
  application:
    name: favourite-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
    registerwitheureka: true
  instance:
    hostname: localhost