server:
  port: 8085
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/admin-service
  application:
    name: search-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
    registerwitheureka: true
  instance:
    hostname: localhost